controller_joint_names: ['', 'front_right_axis_joint', 'front_right_wheel_joint', 'front_left_axis_joint', 'front_left_wheel_joint', 'back_right_axis_joint', 'back_right_wheel_joint', 'back_left_axis_joint', 'back_left_wheel_joint', ]
